name: Cypress Tests with Install Job and UI Chrome Job x 5

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        # containers: [1, 2, 3, 4, 5]
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4.2.0
        with:
          runTests: false
          build: npm install

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4.2.0
        with:
          install: false
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
