name: Cypress Tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4.2.0
        with:
          runTests: false
          build: npm install

      - name: Save node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          if-no-files-found: error
          path: node_modules

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # containers: [1, 2, 3, 4, 5]
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4.2.0
        with:
          install: false
          start: npm run cy:run
          # wait-on: 'http://localhost:3000'
          # wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
