name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4

      - name: Generate test report
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/mochawesome.json
          npx marge -o cypress/reports/results cypress/reports/mochawesome.json

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/results
